version: '3.9'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - prestus-network

  microservice-jobs:
    image: flaviojcordeiro/microservice-jobs:latest
    ports:
      - "3001:3001"
    networks:
      - prestus-network
    environment:
      PORT: 3001
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DB_NAME: ${MONGODB_DB_NAME:-prestus}
      MONGODB_COLLECTION: ${MONGODB_COLLECTION:-jobs}

  microservice-bookings:
    image: flaviojcordeiro/microservice-bookings:latest
    ports:
      - "3002:3002"
    networks:
      - prestus-network
    environment:
      PORT: 3002
      SQL_SERVER: ${SQL_SERVER}
      SQL_DATABASE: ${SQL_DATABASE}
      SQL_USER: ${SQL_USER}
      SQL_PASSWORD: ${SQL_PASSWORD}
      SQL_PORT: ${SQL_PORT:-1433}
      SQL_ENCRYPT: ${SQL_ENCRYPT:-true}
      SQL_TRUST_SERVER_CERT: ${SQL_TRUST_SERVER_CERT:-false}

  function-payment:
    image: flaviojcordeiro/function-payment:latest
    ports:
      - "7071:80"
    networks:
      - prestus-network
    environment:
      AzureWebJobsStorage: UseDevelopmentStorage=true
      FUNCTIONS_WORKER_RUNTIME: node
      WEBSITES_PORT: 80

  function-notification:
    image: flaviojcordeiro/function-notification:latest
    ports:
      - "7072:80"
    networks:
      - prestus-network
    environment:
      AzureWebJobsStorage: UseDevelopmentStorage=true
      FUNCTIONS_WORKER_RUNTIME: node
      WEBSITES_PORT: 80
      NOTIFICATION_PROVIDER: console
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DB_NAME: ${MONGODB_DB_NAME:-prestus}
      MONGODB_COLLECTION: ${MONGODB_NOTIFICATION_COLLECTION:-notifications}

  bff-gateway:
    image: flaviojcordeiro/bff-gateway:latest
    ports:
      - "3000:3000"
    networks:
      - prestus-network
    environment:
      PORT: 3000
      JOBS_SERVICE_URL: http://microservice-jobs:3001
      BOOKINGS_SERVICE_URL: http://microservice-bookings:3002
      NOTIFICATION_FUNCTION_URL: http://function-notification:80/api/send-notification
      PAYMENT_FUNCTION_URL: http://function-payment:80/api/process-payment

  microfrontend:
    image: flaviojcordeiro/microfrontend:latest
    ports:
      - "8080:80"
    networks:
      - prestus-network
    depends_on:
      - bff-gateway

volumes:
  mongodb_data:

networks:
  prestus-network:
    driver: bridge
